---
- name: Install python selinux lib
  yum:
    name: libselinux-python
- name: Get SELinux config
  command: getenforce
  register: selinux_status

- name: Disable selinux on RedHat
  selinux:
    state: disabled
  when: ansible_os_family == 'RedHat' and selinux_status.stdout != 'Disabled'